### ISSUE TITLE
Reformat FAQ to be visible on the Wiki

### ISSUE THREAD

**Issue by pynchmeister** [zapproject/docs#6]
https://github.com/zapproject/docs/wiki/FAQ

**Comment by pynchmeister** [comment]
@Lloyd1553

**Comment by BrianBalayon** [comment]
# Potential Duplicate Work

## Alpha.Zap.Org Use
Besides linking it to the external Google Doc, I am attempting to add an on-site version. 
The built-in docs renders markdown for ease of editing. 

## Why I brought this up
@pynchmeister this is all I could find on the FAQ. 
Half way though adding this to the site I found this issue, and the FAQ is almost fully translated into markdown.

**Comment by pynchmeister** [comment]
Thanks for the heads up @BrianBalayon , good work
